
[[annexA]]
[appendix,obligation=normative,type=justification]
== {blank}

// Base text: indicates where in this document the proposed document text is. The following is the default value reflecting
// how this template has been set up.
[type=basetext]
=== {blank}

Annex B of this Contribution


// *Scope* (defines the intent or object of the {{ doctype }} and the aspects covered, thereby indicating the limits of its applicability):
[type=scope]
=== {blank}

TODO: ensuring organizations are reaching the MVSP level and as such are not vulnerable to the ...

// *Summary* (provides a brief overview of the purpose and contents of the {{ doctype }}, thus permitting readers to judge its usefulness for their work):
[type=summary]
=== {blank}

In this recommendation, we cover Minimum Viable Secure Product (MVSP), a list of essential application security controls. The control groups include business, application design, implementation, and operational controls. In clause 6 the draft recommendation is included with control descriptions and Annex A provides a reasoning for each contro detailing what the control measures and why it should be included. The recommenadtion also addresses the formal requirements, including definitions, abbreviations, terms used.

// *Relations to ITU-T Recommendations or to other standards* (approved or under development):
[type=relatedstandards]
=== {blank}

N/A

// *Liaisons with other study groups or with other standards bodies:*
[type=liaisons]
=== {blank}

N/A

// *Supporting members that are committing to contributing actively to the work item:*
[type=supportingmembers]
=== {blank}

Google Inc., Broadcom, TODO: get support during proposal

